In [3]:
import pandas as pd
df = pd.read_parquet("data/raw/disease/disease.parquet")

In [4]:
print(f"Shape : {df.shape   }")
print(f"Columns : {df.columns}")

Shape : (28513, 14)
Columns : Index(['id', 'code', 'name', 'description', 'dbXRefs', 'parents', 'synonyms',
       'obsoleteTerms', 'obsoleteXRefs', 'children', 'ancestors',
       'therapeuticAreas', 'descendants', 'ontology'],
      dtype='str')

In [5]:
df.head(3)

,id,code,name,description,dbXRefs,parents,synonyms,obsoleteTerms,obsoleteXRefs,children,ancestors,therapeuticAreas,descendants,ontology
0,DOID_0050890,http://purl.obolibrary.org/obo/DOID_0050890,synucleinopathy,A neurodegenerative disease that is characteri...,"[MEDGEN:1682194, UMLS:C5191670, MESH:D00008087...","[MONDO_0019052, MONDO_0021179, MONDO_0024237]","{'hasExactSynonym': ['synucleinopathy', 'alpha...",[],[],"[EFO_0006792, EFO_1001050]","[MONDO_0100545, EFO_0000508, MONDO_0021179, EF...","[EFO_0000618, OTAR_0000020, OTAR_0000018]","[MONDO_0010080, EFO_1001050, MONDO_0016418, EF...","{'isTherapeuticArea': False, 'leaf': False, 's..."
1,DOID_10113,http://purl.obolibrary.org/obo/DOID_10113,trypanosomiasis,Infection with protozoa of the genus trypanosoma.,"[SCTID:78940002, SNOMEDCT:78940002, NANDO:2200...",[MONDO_0002428],{'hasExactSynonym': ['Trypanosoma disease or d...,[],[],"[MONDO_0001444, EFO_0005225, EFO_0008559]","[EFO_0001067, MONDO_0002428, EFO_0005741]",[EFO_0005741],"[EFO_0005225, MONDO_0001444, EFO_0005529, EFO_...","{'isTherapeuticArea': False, 'leaf': False, 's..."
2,DOID_10718,http://purl.obolibrary.org/obo/DOID_10718,giardiasis,An infection of the small intestine caused by ...,"[SNOMEDCT:10679007, MESH:D005873, MeSH:D005873...","[MONDO_0002428, EFO_0009561]","{'hasExactSynonym': ['beaver feaver', 'giardia...",[],[],[],"[MONDO_0002428, EFO_0009561, EFO_0001067, EFO_...","[EFO_0010282, EFO_0005741]",[],"{'isTherapeuticArea': False, 'leaf': False, 's..."

In [6]:
df[df['name'].str.contains('Alzheimer', case=False, na=False)][['name', 'parents', 'ancestors']].head(20)

,name,parents,ancestors
4289,Alzheimer disease,"[MONDO_0001627, EFO_0005815]","[MONDO_0002039, EFO_0005815, EFO_0005772, EFO_..."
4370,Alzheimer disease type 1,[MONDO_0015140],"[MONDO_0024237, MONDO_0100087, EFO_0009386, EF..."
6961,Alzheimer disease 3,[MONDO_0015140],"[MONDO_0100087, EFO_0005815, OTAR_0000018, MON..."
8087,Alzheimer disease 18,"[MONDO_0004975, MONDO_0015547, MONDO_0024237]","[MONDO_0024237, EFO_0000508, MONDO_0001627, EF..."
8524,early-onset autosomal dominant Alzheimer disease,"[MONDO_0000426, MONDO_0100087]","[MONDO_0024237, EFO_0000508, MONDO_0015547, MO..."
12982,familial Alzheimer disease,"[MONDO_0004975, MONDO_0015547, MONDO_0024237]","[EFO_0009386, EFO_0000677, EFO_0000618, EFO_00..."
13778,age of onset of Alzheimer disease,[OBA_2040165],"[EFO_0001444, HP_0003674, EFO_0004949, EFO_000..."
15284,Alzheimer's disease biomarker measurement,[EFO_0006848],"[EFO_0006848, EFO_0001444]"
15324,Alzheimer's disease neuropathologic change,"[EFO_0003765, EFO_0009386]","[EFO_0009386, EFO_0000651, EFO_0000618, EFO_00..."
17081,family history of Alzheimer’s disease,[EFO_0006514],"[EFO_0006848, EFO_0006514, EFO_0001444]"
26296,late-onset Alzheimers disease,[MONDO_0004975],"[EFO_0009386, EFO_0005774, EFO_0005815, EFO_00..."

In [7]:
df[df['id'] =='MONDO_0001627'][['id', 'name', 'description']]

,id,name,description
2839,MONDO_0001627,dementia,Loss of intellectual abilities interfering wit...

In [9]:
df[df['name']=='giardiasis'][['id', 'name', 'description']]

           id        name                                        description
2  DOID_10718  giardiasis  An infection of the small intestine caused by ...

In [10]:
diseases = pd.read_parquet("data/raw/disease/")
targets = pd.read_parquet("data/raw/target/")
associations = pd.read_parquet("data/raw/association_overall_direct/")

In [11]:
print("Diseases: ", diseases.shape, "->", diseases.columns.to_list()[:5])
print("Targets: ", targets.shape, "->", targets.columns.to_list()[:5])
print("Associations: ", associations.shape, "->", associations.columns.to_list()[:5])

Diseases:  (28513, 14) -> ['id', 'code', 'name', 'description', 'dbXRefs']
Targets:  (78766, 29) -> ['id', 'approvedSymbol', 'biotype', 'transcriptIds', 'canonicalTranscript']
Associations:  (3628026, 4) -> ['diseaseId', 'targetId', 'score', 'evidenceCount']

In [15]:
alzheimer_id = diseases[diseases['name'] == 'Alzheimer disease']['id'].iloc[0]
alz_associations = associations[associations['diseaseId'] == alzheimer_id]

In [19]:
alz_targets = targets.merge(alz_associations, left_on='id', right_on='targetId')

In [26]:
alz_targets.sort_values(by = ['score'],ascending = False)[:10]

,id,approvedSymbol,biotype,transcriptIds,canonicalTranscript,canonicalExons,genomicLocation,alternativeGenes,approvedName,go,...,chemicalProbes,homologues,tractability,safetyLiabilities,pathways,tss,diseaseId,targetId,score,evidenceCount
11206,ENSG00000142192,APP,protein_coding,"[ENST00000462267, ENST00000464867, ENST0000044...","{'id': 'ENST00000346798', 'chromosome': '21', ...","[25997360, 25997416, 26000015, 26000182, 26170...","{'chromosome': '21', 'start': 25880535, 'end':...",None,amyloid beta precursor protein,"[{'id': 'GO:0005515', 'source': 'PMID:14527950...",...,None,"[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...",None,"[{'pathwayId': 'R-HSA-3000178', 'pathway': 'EC...",26170770.0,MONDO_0004975,ENSG00000142192,0.778499,22433
3799,ENSG00000064687,ABCA7,protein_coding,"[ENST00000263094, ENST00000673773, ENST0000052...","{'id': 'ENST00000263094', 'chromosome': '19', ...","[1042315, 1042397, 1040107, 1040196, 1046802, ...","{'chromosome': '19', 'start': 1039997, 'end': ...",None,ATP binding cassette subfamily A member 7,"[{'id': 'GO:0034205', 'source': 'PMID:26260791...",...,None,"[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...",None,"[{'pathwayId': 'R-HSA-1369062', 'pathway': 'AB...",1040107.0,MONDO_0004975,ENSG00000064687,0.707360,460
5214,ENSG00000130203,APOE,protein_coding,"[ENST00000485628, ENST00000252486, ENST0000043...","{'id': 'ENST00000252486', 'chromosome': '19', ...","[44907760, 44907952, 44908533, 44909393, 44905...","{'chromosome': '19', 'start': 44905791, 'end':...",None,apolipoprotein E,"[{'id': 'GO:0005576', 'source': 'Reactome:R-HS...",...,None,"[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...","[{'event': 'hemorrhage', 'eventId': 'MP_000191...","[{'pathwayId': 'R-HSA-1251985', 'pathway': 'Nu...",44905796.0,MONDO_0004975,ENSG00000130203,0.692288,15670
2396,ENSG00000176884,GRIN1,protein_coding,"[ENST00000676396, ENST00000371553, ENST0000046...","{'id': 'ENST00000371561', 'chromosome': '9', '...","[137165186, 137165296, 137163759, 137163904, 1...","{'chromosome': '9', 'start': 137138346, 'end':...",None,glutamate ionotropic receptor NMDA type subunit 1,"[{'id': 'GO:0004972', 'source': 'GO_REF:000003...",...,None,"[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...","[{'event': 'neurotoxicity', 'eventId': 'EFO_00...","[{'pathwayId': 'R-HSA-438066', 'pathway': 'Unb...",137139154.0,MONDO_0004975,ENSG00000176884,0.683561,129
7527,ENSG00000164885,CDK5,protein_coding,"[ENST00000485972, ENST00000476691, ENST0000046...","{'id': 'ENST00000485972', 'chromosome': '7', '...","[151054212, 151054292, 151055277, 151055373, 1...","{'chromosome': '7', 'start': 151053815, 'end':...",None,cyclin dependent kinase 5,"[{'id': 'GO:0005737', 'source': 'GO_REF:000003...",...,"[{'control': None, 'drugId': 'CHEMBL5078192', ...","[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...",None,"[{'pathwayId': 'R-HSA-983231', 'pathway': 'Fac...",151057897.0,MONDO_0004975,ENSG00000164885,0.679588,738
9932,ENSG00000137642,SORL1,protein_coding,"[ENST00000260197, ENST00000534286, ENST0000052...","{'id': 'ENST00000260197', 'chromosome': '11', ...","[121559519, 121559657, 121570157, 121570270, 1...","{'chromosome': '11', 'start': 121452314, 'end'...",None,sortilin related receptor 1,"[{'id': 'GO:0005768', 'source': 'PMID:16174740...",...,None,"[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...",None,"[{'pathwayId': 'R-HSA-977225', 'pathway': 'Amy...",121452314.0,MONDO_0004975,ENSG00000137642,0.660465,648
5827,ENSG00000087085,ACHE,protein_coding,"[ENST00000419336, ENST00000412389, ENST0000024...","{'id': 'ENST00000241069', 'chromosome': '7', '...","[100889994, 100890335, 100895802, 100895888, 1...","{'chromosome': '7', 'start': 100889994, 'end':...",None,acetylcholinesterase (Yt blood group),"[{'id': 'GO:0048471', 'source': 'PMID:14766237...",...,"[{'control': None, 'drugId': 'CHEMBL1196204', ...","[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...","[{'event': 'Decrease, Population growth rate',...","[{'pathwayId': 'R-HSA-422085', 'pathway': 'Syn...",100895888.0,MONDO_0004975,ENSG00000087085,0.627685,5940
5011,ENSG00000114200,BCHE,protein_coding,"[ENST00000497011, ENST00000264381, ENST0000048...","{'id': 'ENST00000264381', 'chromosome': '3', '...","[165829517, 165831041, 165772904, 165773506, 1...","{'chromosome': '3', 'start': 165772904, 'end':...",None,butyrylcholinesterase,"[{'id': 'GO:0005576', 'source': 'PMID:14718574...",...,None,"[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...","[{'event': 'apnea', 'eventId': 'HP_0002104', '...","[{'pathwayId': 'R-HSA-422085', 'pathway': 'Syn...",165837423.0,MONDO_0004975,ENSG00000114200,0.620249,3802
8522,ENSG00000138613,APH1B,protein_coding,"[ENST00000261879, ENST00000559744, ENST0000038...","{'id': 'ENST00000261879', 'chromosome': '15', ...","[63305614, 63309126, 63277605, 63277736, 63279...","{'chromosome': '15', 'start': 63276018, 'end':...",None,"aph-1 homolog B, gamma-secretase subunit","[{'id': 'GO:0042987', 'source': 'PMID:12763021...",...,None,"[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...",None,"[{'pathwayId': 'R-HSA-1251985', 'pathway': 'Nu...",63277605.0,MONDO_0004975,ENSG00000138613,0.611217,52
417,ENSG00000273079,GRIN2B,protein_coding,"[ENST00000714048, ENST00000637214, ENST0000062...","{'id': 'ENST00000609686', 'chromosome': '12', ...","[13567025, 13567263, 13608603, 13608832, 13616...","{'chromosome': '12', 'start': 13437942, 'end':...",None,glutamate ionotropic receptor NMDA type subuni...,"[{'id': 'GO:0005515', 'source': 'PMID:20018661...",...,"[{'control': None, 'drugId': 'CHEMBL48029', 'i...","[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...","[{'event': 'impaired social interactions', 'ev...","[{'pathwayId': 'R-HSA-9022699', 'pathway': 'ME...",13981602.0,MONDO_0004975,ENSG00000273079,0.609707,218