In [7]:
import pandas as pd
df = pd.read_parquet("data/raw/disease/disease.parquet")

In [9]:
print(f"Shape : {df.shape   }")
print(f"Columns : {df.columns}")

Shape : (28513, 14)
Columns : Index(['id', 'code', 'name', 'description', 'dbXRefs', 'parents', 'synonyms',
       'obsoleteTerms', 'obsoleteXRefs', 'children', 'ancestors',
       'therapeuticAreas', 'descendants', 'ontology'],
      dtype='str')

In [10]:
df.head(3)

,id,code,name,description,dbXRefs,parents,synonyms,obsoleteTerms,obsoleteXRefs,children,ancestors,therapeuticAreas,descendants,ontology
0,DOID_0050890,http://purl.obolibrary.org/obo/DOID_0050890,synucleinopathy,A neurodegenerative disease that is characteri...,"[MEDGEN:1682194, UMLS:C5191670, MESH:D00008087...","[MONDO_0019052, MONDO_0021179, MONDO_0024237]","{'hasExactSynonym': ['synucleinopathy', 'alpha...",[],[],"[EFO_0006792, EFO_1001050]","[MONDO_0100545, EFO_0000508, MONDO_0021179, EF...","[EFO_0000618, OTAR_0000020, OTAR_0000018]","[MONDO_0010080, EFO_1001050, MONDO_0016418, EF...","{'isTherapeuticArea': False, 'leaf': False, 's..."
1,DOID_10113,http://purl.obolibrary.org/obo/DOID_10113,trypanosomiasis,Infection with protozoa of the genus trypanosoma.,"[SCTID:78940002, SNOMEDCT:78940002, NANDO:2200...",[MONDO_0002428],{'hasExactSynonym': ['Trypanosoma disease or d...,[],[],"[MONDO_0001444, EFO_0005225, EFO_0008559]","[EFO_0001067, MONDO_0002428, EFO_0005741]",[EFO_0005741],"[EFO_0005225, MONDO_0001444, EFO_0005529, EFO_...","{'isTherapeuticArea': False, 'leaf': False, 's..."
2,DOID_10718,http://purl.obolibrary.org/obo/DOID_10718,giardiasis,An infection of the small intestine caused by ...,"[SNOMEDCT:10679007, MESH:D005873, MeSH:D005873...","[MONDO_0002428, EFO_0009561]","{'hasExactSynonym': ['beaver feaver', 'giardia...",[],[],[],"[MONDO_0002428, EFO_0009561, EFO_0001067, EFO_...","[EFO_0010282, EFO_0005741]",[],"{'isTherapeuticArea': False, 'leaf': False, 's..."

In [17]:
df[df['name'].str.contains('Alzheimer', case=False, na=False)][['name', 'parents', 'ancestors']].head(20)

,name,parents,ancestors
4289,Alzheimer disease,"[MONDO_0001627, EFO_0005815]","[MONDO_0002039, EFO_0005815, EFO_0005772, EFO_..."
4370,Alzheimer disease type 1,[MONDO_0015140],"[MONDO_0024237, MONDO_0100087, EFO_0009386, EF..."
6961,Alzheimer disease 3,[MONDO_0015140],"[MONDO_0100087, EFO_0005815, OTAR_0000018, MON..."
8087,Alzheimer disease 18,"[MONDO_0004975, MONDO_0015547, MONDO_0024237]","[MONDO_0024237, EFO_0000508, MONDO_0001627, EF..."
8524,early-onset autosomal dominant Alzheimer disease,"[MONDO_0000426, MONDO_0100087]","[MONDO_0024237, EFO_0000508, MONDO_0015547, MO..."
12982,familial Alzheimer disease,"[MONDO_0004975, MONDO_0015547, MONDO_0024237]","[EFO_0009386, EFO_0000677, EFO_0000618, EFO_00..."
13778,age of onset of Alzheimer disease,[OBA_2040165],"[EFO_0001444, HP_0003674, EFO_0004949, EFO_000..."
15284,Alzheimer's disease biomarker measurement,[EFO_0006848],"[EFO_0006848, EFO_0001444]"
15324,Alzheimer's disease neuropathologic change,"[EFO_0003765, EFO_0009386]","[EFO_0009386, EFO_0000651, EFO_0000618, EFO_00..."
17081,family history of Alzheimer’s disease,[EFO_0006514],"[EFO_0006848, EFO_0006514, EFO_0001444]"
26296,late-onset Alzheimers disease,[MONDO_0004975],"[EFO_0009386, EFO_0005774, EFO_0005815, EFO_00..."

In [13]:
df[df['id'] =='MONDO_0001627'][['id', 'name', 'description']]

,id,name,description
2839,MONDO_0001627,dementia,Loss of intellectual abilities interfering wit...

In [ ]:
df

,id,code,name,description,dbXRefs,parents,synonyms,obsoleteTerms,obsoleteXRefs,children,ancestors,therapeuticAreas,descendants,ontology
0,DOID_0050890,http://purl.obolibrary.org/obo/DOID_0050890,synucleinopathy,A neurodegenerative disease that is characteri...,"[MEDGEN:1682194, UMLS:C5191670, MESH:D00008087...","[MONDO_0019052, MONDO_0021179, MONDO_0024237]","{'hasExactSynonym': ['synucleinopathy', 'alpha...",[],[],"[EFO_0006792, EFO_1001050]","[MONDO_0100545, EFO_0000508, MONDO_0021179, EF...","[EFO_0000618, OTAR_0000020, OTAR_0000018]","[MONDO_0010080, EFO_1001050, MONDO_0016418, EF...","{'isTherapeuticArea': False, 'leaf': False, 's..."
1,DOID_10113,http://purl.obolibrary.org/obo/DOID_10113,trypanosomiasis,Infection with protozoa of the genus trypanosoma.,"[SCTID:78940002, SNOMEDCT:78940002, NANDO:2200...",[MONDO_0002428],{'hasExactSynonym': ['Trypanosoma disease or d...,[],[],"[MONDO_0001444, EFO_0005225, EFO_0008559]","[EFO_0001067, MONDO_0002428, EFO_0005741]",[EFO_0005741],"[EFO_0005225, MONDO_0001444, EFO_0005529, EFO_...","{'isTherapeuticArea': False, 'leaf': False, 's..."
2,DOID_10718,http://purl.obolibrary.org/obo/DOID_10718,giardiasis,An infection of the small intestine caused by ...,"[SNOMEDCT:10679007, MESH:D005873, MeSH:D005873...","[MONDO_0002428, EFO_0009561]","{'hasExactSynonym': ['beaver feaver', 'giardia...",[],[],[],"[MONDO_0002428, EFO_0009561, EFO_0001067, EFO_...","[EFO_0010282, EFO_0005741]",[],"{'isTherapeuticArea': False, 'leaf': False, 's..."
3,DOID_13406,http://purl.obolibrary.org/obo/DOID_13406,pulmonary sarcoidosis,Sarcoidosis affecting the lung parenchyma. It ...,"[ICD9:517.8, SNOMEDCT:24369008, UMLS:C0036205,...","[MONDO_0017026, MONDO_0019338]","{'hasExactSynonym': ['sarcoidosis of lung', 'S...",[],[],[EFO_1001232],"[EFO_0009433, MONDO_0019751, EFO_0002461, MOND...","[OTAR_0000010, OTAR_0000006]",[EFO_1001232],"{'isTherapeuticArea': False, 'leaf': False, 's..."
4,DOID_1947,http://purl.obolibrary.org/obo/DOID_1947,trichomoniasis,An infection that is caused by Trichomonas.,"[DOID:1947, ICD9:131.9, SCTID:56335008, NCIt:C...",[MONDO_0002428],"{'hasExactSynonym': ['trichomoniasis', 'Tricho...",[],[],"[MONDO_0030705, MONDO_0030707, MONDO_0030708, ...","[MONDO_0002428, EFO_0005741, EFO_0001067]",[EFO_0005741],"[EFO_0007521, MONDO_0030720, MONDO_0030705, MO...","{'isTherapeuticArea': False, 'leaf': False, 's..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28508,Orphanet_99942,http://www.orpha.net/ORDO/Orphanet_99942,Autosomal dominant Charcot-Marie-Tooth disease...,Autosomal dominant Charcot-Marie-Tooth disease...,"[ICD10:G60.0, OMIM:607677]",[MONDO_0018993],"{'hasExactSynonym': ['CMT2I'], 'hasRelatedSyno...",[],[],[],"[EFO_0004149, MONDO_0018993, MONDO_0100546, MO...","[EFO_0000618, OTAR_0000018]",[],"{'isTherapeuticArea': False, 'leaf': False, 's..."
28509,Orphanet_99943,http://www.orpha.net/ORDO/Orphanet_99943,Autosomal dominant Charcot-Marie-Tooth disease...,Autosomal dominant Charcot-Marie-Tooth disease...,"[ICD10:G60.0, OMIM:607736]",[MONDO_0018993],"{'hasExactSynonym': ['CMT2J'], 'hasRelatedSyno...",[],[],[],"[EFO_0009387, EFO_0004149, OTAR_0000018, EFO_0...","[EFO_0000618, OTAR_0000018]",[],"{'isTherapeuticArea': False, 'leaf': False, 's..."
28510,Orphanet_99945,http://www.orpha.net/ORDO/Orphanet_99945,Autosomal dominant Charcot-Marie-Tooth disease...,Autosomal dominant Charcot-Marie-Tooth disease...,"[OMIM:608673, ICD10:G60.0]",[MONDO_0018993],"{'hasExactSynonym': ['CMT2L'], 'hasRelatedSyno...",[],[],[],"[EFO_1001902, EFO_0000618, EFO_0009387, MONDO_...","[OTAR_0000018, EFO_0000618]",[],"{'isTherapeuticArea': False, 'leaf': False, 's..."
28511,Orphanet_99946,http://www.orpha.net/ORDO/Orphanet_99946,Autosomal dominant Charcot-Marie-Tooth disease...,Autosomal dominant Charcot-Marie-Tooth disease...,"[ICD10:G60.0, OMIM:118210]",[MONDO_0018993],"{'hasExactSynonym': ['CMT2A1'], 'hasRelatedSyn...",[],[],[],"[MONDO_0020127, MONDO_0100546, EFO_0004149, MO...","[OTAR_0000018, EFO_0000618]",[],"{'isTherapeuticArea': False, 'leaf': False, 's..."
28512,Orphanet_99947,http://www.orpha.net/ORDO/Orphanet_99947,Autosomal dominant Charcot-Marie-Tooth disease...,NaN,"[ICD10:G60.0, OMIM:609260]",[MONDO_0018993],{'hasExactSynonym': ['Charcot-Marie-Tooth dise...,[],[],[],"[MONDO_0015626, MONDO_0018993, EFO_0000618, EF...","[EFO_0000618, OTAR_0000018]",[],"{'isTherapeuticArea': False, 'leaf': False, 's..."

In [19]:
df[df['name']=='giardiasis'][['id', 'name', 'description']]

           id        name                                        description
2  DOID_10718  giardiasis  An infection of the small intestine caused by ...

In [21]:
diseases = pd.read_parquet("data/raw/disease/")
targets = pd.read_parquet("data/raw/target/")
associations = pd.read_parquet("data/raw/association_overall_direct/")

In [22]:
print("Diseases: ", diseases.shape, "->", diseases.columns.to_list()[:5])
print("Targets: ", targets.shape, "->", targets.columns.to_list()[:5])
print("Associations: ", associations.shape, "->", associations.columns.to_list()[:5])

Diseases:  (28513, 14) -> ['id', 'code', 'name', 'description', 'dbXRefs']
Targets:  (78766, 29) -> ['id', 'approvedSymbol', 'biotype', 'transcriptIds', 'canonicalTranscript']
Associations:  (3628026, 4) -> ['diseaseId', 'targetId', 'score', 'evidenceCount']

In [30]:
diseases.head(3)

,id,code,name,description,dbXRefs,parents,synonyms,obsoleteTerms,obsoleteXRefs,children,ancestors,therapeuticAreas,descendants,ontology
0,DOID_0050890,http://purl.obolibrary.org/obo/DOID_0050890,synucleinopathy,A neurodegenerative disease that is characteri...,"[MEDGEN:1682194, UMLS:C5191670, MESH:D00008087...","[MONDO_0019052, MONDO_0021179, MONDO_0024237]","{'hasExactSynonym': ['synucleinopathy', 'alpha...",[],[],"[EFO_0006792, EFO_1001050]","[MONDO_0100545, EFO_0000508, MONDO_0021179, EF...","[EFO_0000618, OTAR_0000020, OTAR_0000018]","[MONDO_0010080, EFO_1001050, MONDO_0016418, EF...","{'isTherapeuticArea': False, 'leaf': False, 's..."
1,DOID_10113,http://purl.obolibrary.org/obo/DOID_10113,trypanosomiasis,Infection with protozoa of the genus trypanosoma.,"[SCTID:78940002, SNOMEDCT:78940002, NANDO:2200...",[MONDO_0002428],{'hasExactSynonym': ['Trypanosoma disease or d...,[],[],"[MONDO_0001444, EFO_0005225, EFO_0008559]","[EFO_0001067, MONDO_0002428, EFO_0005741]",[EFO_0005741],"[EFO_0005225, MONDO_0001444, EFO_0005529, EFO_...","{'isTherapeuticArea': False, 'leaf': False, 's..."
2,DOID_10718,http://purl.obolibrary.org/obo/DOID_10718,giardiasis,An infection of the small intestine caused by ...,"[SNOMEDCT:10679007, MESH:D005873, MeSH:D005873...","[MONDO_0002428, EFO_0009561]","{'hasExactSynonym': ['beaver feaver', 'giardia...",[],[],[],"[MONDO_0002428, EFO_0009561, EFO_0001067, EFO_...","[EFO_0010282, EFO_0005741]",[],"{'isTherapeuticArea': False, 'leaf': False, 's..."

In [31]:
targets.head(3)

,id,approvedSymbol,biotype,transcriptIds,canonicalTranscript,canonicalExons,genomicLocation,alternativeGenes,approvedName,go,...,constraint,tep,proteinIds,dbXrefs,chemicalProbes,homologues,tractability,safetyLiabilities,pathways,tss
0,ENSG00000020219,CCT8L1P,processed_pseudogene,[ENST00000465400],"{'id': 'ENST00000465400', 'chromosome': '7', '...","[152445477, 152447150]","{'chromosome': '7', 'start': 152445477, 'end':...",None,"chaperonin containing TCP1 subunit 8 like 1, p...",None,...,None,None,"[{'id': 'A6NM43', 'source': 'uniprot_obsolete'}]","[{'id': '32153', 'source': 'HGNC'}, {'id': 'IP...",None,None,None,None,None,152445477.0
1,ENSG00000059588,TARBP1,protein_coding,"[ENST00000471918, ENST00000040877, ENST0000046...","{'id': 'ENST00000040877', 'chromosome': '1', '...","[234420702, 234420812, 234425673, 234425793, 2...","{'chromosome': '1', 'start': 234391313, 'end':...",None,tRNA guanosine 2 -O-methyltransferase TARBP1,"[{'id': 'GO:0006357', 'source': 'PMID:8846792'...",...,"[{'constraintType': 'syn', 'score': 0.88121002...",None,"[{'id': 'Q13395', 'source': 'uniprot_swissprot...","[{'id': '11568', 'source': 'HGNC'}, {'id': '2H...",None,"[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...",None,None,234479179.0
2,ENSG00000070182,SPTB,protein_coding,"[ENST00000389720, ENST00000542694, ENST0000055...","{'id': 'ENST00000644917', 'chromosome': '14', ...","[64785537, 64785627, 64774397, 64774527, 64769...","{'chromosome': '14', 'start': 64746283, 'end':...",None,"spectrin beta, erythrocytic","[{'id': 'GO:0030506', 'source': 'PMID:8159688'...",...,"[{'constraintType': 'syn', 'score': -2.2815999...",None,"[{'id': 'P11277', 'source': 'uniprot_swissprot...","[{'id': '11274', 'source': 'HGNC'}, {'id': '1S...",None,"[{'speciesId': '9606', 'speciesName': 'Human',...","[{'modality': 'SM', 'id': 'Approved Drug', 'va...",None,"[{'pathwayId': 'R-HSA-6807878', 'pathway': 'CO...",64879907.0

In [43]:
associations

              diseaseId         targetId     score  evidenceCount
0          DOID_0050890  ENSG00000001084  0.031799              4
1          DOID_0050890  ENSG00000004142  0.002217              1
2          DOID_0050890  ENSG00000004478  0.002217              1
3          DOID_0050890  ENSG00000004948  0.002957              1
4          DOID_0050890  ENSG00000005381  0.002217              1
...                 ...              ...       ...            ...
3628021  Orphanet_99946  ENSG00000172409  0.039183              1
3628022  Orphanet_99946  ENSG00000179902  0.063280              4
3628023  Orphanet_99946  ENSG00000196876  0.041851              1
3628024  Orphanet_99947  ENSG00000101986  0.033780              1
3628025  Orphanet_99947  ENSG00000104833  0.032360              1

[3628026 rows x 4 columns]

In [70]:
alzheimer_id = diseases[diseases['name'] == 'Alzheimer disease']['id'].iloc[0]
alz_associations = associations[associations['diseaseId'] == alzheimer_id]

In [71]:
targets = targets.merge(alz_associations,left_on = 'targetId', right_on = 'targetId')

KeyError: 'targetId'

In [67]:
alz_associations

             diseaseId         targetId     score  evidenceCount
2384547  MONDO_0004975  ENSG00000000003  0.021719             10
2384548  MONDO_0004975  ENSG00000000005  0.007946              2
2384549  MONDO_0004975  ENSG00000000419  0.006098              2
2384550  MONDO_0004975  ENSG00000000457  0.260689              1
2384551  MONDO_0004975  ENSG00000000460  0.004989              2
...                ...              ...       ...            ...
2396838  MONDO_0004975  ENSG00000277791  0.009833              7
2396839  MONDO_0004975  ENSG00000284387  0.008870              1
2396840  MONDO_0004975  ENSG00000284770  0.056777             35
2396841  MONDO_0004975  ENSG00000291148  0.001478              1
2396842  MONDO_0004975  ENSG00000293392  0.001478              1

[12256 rows x 4 columns]